# Generated by Django 4.1.3 on 2022-11-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('emp_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=2)),
            ],
        ),
    ]
